use databaseproject;

show tables;

INSERT INTO WXY_TRIP (TRIP_ID, NIGHTS_NUM)
VALUES (1, 5);

INSERT INTO WXY_CRUISE (cruise_id, cruise_name, trip_id)
VALUES (1, 'Black Pearl', 1);

INSERT INTO WXY_STATEROOM (ROOM_ID, TYPE, SIZE, BED_NUM, BATHROOM_NUM, BALCONY, PRICE_PER_PERSON, POSITION, cruise_id)
VALUES (1, 'The Haven Suite', 1000, 6, 3, 2, 500.1, 'Forward', 1);

INSERT INTO WXY_RESTAURANT (RESTAURANT_ID, TYPE, START_TIME, END_TIME, FLOOR, cruise_id)
VALUES (1, 'Common Buffett', '2024-11-10 07:00:00', '2024-11-10  21:00:00', 6, 1);

INSERT INTO wxy_package (PACKAGE_ID, TYPE, PRICE)
VALUES (1, 'Water and Non-Alcoholic', 40);

INSERT INTO WXY_ENTERTAINMENT (ENTERTAINMENT_ID, TYPE, UNITS_NUM, FLOOR_1, FLOOR_2, FLOOR_3, AGE_LIMITS, cruise_id)
VALUES (1, 'Theaters', 2, 8, 10, 2, 2, 1);

INSERT INTO WXY_PORT (PORT_ID, PORT_NAME, STATE, COUNTRY, ADDRESS1, ADDRESS2, NEAREST_AIRPORT_NAME, NUMBER_OF_PARKING_SPOTS)
VALUES (1, 'Port of Miami', 'FL', 'USA', '101 Cruise Blvd', NULL, 'Miami International Airport', 500);

INSERT INTO WXY_TRIP_PORT (TRIP_ID, PORT_ID, TYPE, START_DATE, END_DATE)
VALUES (1, 1, 'start_port', '2024-01-01', '2024-01-01');

INSERT INTO WXY_GROUP (GROUP_ID, TRIP_ID)
VALUES (1, 1);

INSERT INTO WXY_INVOICE (INVOICE_ID, AMOUNT, INVOICE_DATE, GROUP_ID)
VALUES (1, 5000, '2024-01-01', 1);

INSERT INTO WXY_PAYMENT (PAYMENT_ID, INVOICE_ID, AMOUNT, DATE, METHOD)
VALUES (1, 1, 2500, '2024-01-02', 'Credit Card');

INSERT INTO WXY_USER (USER_ID, USER_NAME, PASSWORD, MEMBERSHIP)
VALUES (1, 'Zhangsan','password123', 'Gold');

INSERT INTO WXY_PASSENGER (PASSENGER_ID, FNAME, MNAME, LNAME, BIRTH_DATE, ADDRESS_COUNTRY, ADDRESS_STATE, ADDRESS_CITY, ADDRESS_STREET_1, ADDRESS_STREET_2, GENDER, NATIONALITY, EMAIL, PHONE, USER_ID, GROUP_ID)
VALUES (1, 'John', 'A', 'Doe', '1985-01-01', 'USA', 'CA', 'Los Angeles', '123 Main St', NULL, 'Male', 'American', 'john.doe1@example.com', '1234567890', 1, 1);

INSERT INTO WXY_PASSENGER_ROOM (PASSENGER_ID, room_id, PRICE)
VALUES (1, 1, 1.1);